version: '3.8'

services:
  strapi:
    image: strapi/strapi
    container_name: strapi_postgres_gatsby
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
      - '3000:3000'
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./data:/var/lib/postgresql/data

  gatsby:
    depends_on:
      - strapi
      - postgres
    environment:
      STRAPI_URL: strapi:1337
    build:
      context: ./gatsby
      dockerfile: Dockerfile
    volumes:
      - ./gatsby:/app
    restart: always
    network_mode: "service:strapi"
